apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-2048
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-2048
  template:
    metadata:
      labels:
        app: my-2048
    spec:
      containers:
      - name: my-2048
        image: sdscello/2048:7
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-2048
  labels:
    app: my-2048
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: my-2048
