version: 0.2
phases:
  pre_build:
    commands:
      - $(aws ecr get-login)
      - printenv
  build:
    commands:
      - docker build --tag "${REPOSITORY_URI}:${TAG}" .
  post_build:
    commands:
      - docker push "${REPOSITORY_URI}:${TAG}"
      - printf '{"tag":"%s"}' $TAG > build.json
artifacts:
  files: build.json
