version: 0.2

environment_variables:
  plaintext:
    "ECR_URI": "140594921984.dkr.ecr.ap-northeast-1.amazonaws.com/2048"
    "ECR_TAG": "16"

phases:
  pre_build:
    commands:
      - $(aws ecr get-login)
      - printenv
  build:
    commands:
      - docker build --tag "${ECR_URI}:${ECR_TAG}" .
  post_build:
    commands:
      - docker push "${ECR_URI}:${ECR_TAG}"
      - printf '{"tag":"%s"}' $ECR_TAG > build.json

artifacts:
  files: build.json
