version: 0.2
phases:
  pre_build:
    commands:
      - $(aws ecr get-login)
      - printf '{"tag1":"%s"}' $CODEBUILD_RESOLVED_SOURCE_VERSION
      - printf '{"tag2":"%s"}' $CODEBUILD_SOURCE_VERSION
      - TAG="$(echo $CODEBUILD_SOURCE_VERSION | head -c 8)"
  build:
    commands:
      - docker build --tag "${REPOSITORY_URI}:${TAG}" .
  post_build:
    commands:
      - docker push "${REPOSITORY_URI}:${TAG}"
      - printf '{"tag":"%s"}' $TAG > build.json
artifacts:
  files: build.json
