apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: can-2048-deployment
  labels:
    app: my-2048
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-2048
  template:
    metadata:
      labels:
        app: my-2048
    spec:
      containers:
      - name: my-2048
        image: index.docker.io/sdscello/git-2048
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /
    prometheus.io/port: "8000"
    prometheus.io/scrape: "true"
  name: can-2048-service
  labels:
    app: my-2048
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
  - name: http-metrics
    port: 8000
  selector:
    app: my-2048
