apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-2048
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-2048
  template:
    metadata:
      labels:
        app: my-2048
    spec:
      containers:
      - name: my-2048
        image: 226258797673.dkr.ecr.ap-northeast-2.amazonaws.com/jenkins-ci-test
        ports:
        - containerPort: 80
