apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-2048-deployment
  labels:
    app: my-2048
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-2048
  template:
    metadata:
      labels:
        app: my-2048
    spec:
      containers:
      - name: my-2048
        image: sdscello/git-2048:release-1.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-2048-service
  labels:
    app: my-2048
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: my-2048
