apiVersion: v1
kind: Service
metadata:
  name: my-2048
  namespace: default
spec:
  selector:
    app: my-2048
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-2048
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: my-2048
    spec:
      containers:
      - name: my-2048
        image: sdscello/2048:1
        ports:
        - containerPort: 80
